import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Components/Header";
import Comparator from "@/Components/Comparator";
// import arab from "http://fonts.googleapis.com/earlyaccess/droidarabickufi.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Text Compare",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-customFont">
        <header>
          <Header />
        </header>
        <Comparator />
      </body>
    </html>
  );
}
